'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {resourceMeta} from '@/lib/resource-meta';
import type {Resource} from '@/lib/planner';

export default function ResourceDirectory(){
 const [resources,setResources]=useState<Resource[]>([]),[filters,setFilters]=useState({noAppointment:false,noId:false,fresh:false,spanish:false}),[printId,setPrintId]=useState('');
 useEffect(()=>{fetch('/data/resources.json').then(r=>r.json() as Promise<Resource[]>).then(items=>setResources(items.map(x=>({...x,...resourceMeta[x.id]}))))},[]);
 const shown=useMemo(()=>resources.filter(r=>(!filters.noAppointment||!r.appointment)&&(!filters.noId||r.idRequired!==true)&&(!filters.fresh||r.freshFood===true)&&(!filters.spanish||r.languages?.includes('Spanish'))),[resources,filters]);
 function printCard(id:string){setPrintId(id);setTimeout(()=>window.print(),80)}
 return <main className="directory-shell"><Link href="/">← Back to trip planner</Link><div className="eyebrow">SOURCED GREATER HARTFORD PILOT</div><h1>Food resource directory</h1><p>Filter on recorded attributes and inspect unknown information before travel. “No published ID rule” does not guarantee that identification will never be requested.</p><div className="filter-grid directory-filters">{([{key:'noAppointment',label:'No appointment'},{key:'noId',label:'No published ID rule'},{key:'fresh',label:'Fresh food listed'},{key:'spanish',label:'Spanish available'}] as const).map(x=><button key={x.key} className={filters[x.key]?'active':''} aria-pressed={filters[x.key]} onClick={()=>setFilters(f=>({...f,[x.key]:!f[x.key]}))}>{x.label}</button>)}</div><p><strong>{shown.length}</strong> of {resources.length} resources match.</p><section className="directory-grid">{shown.map(r=><article key={r.id} className={`directory-card ${printId&&printId!==r.id?'no-print':''}`}><h2>{r.name}</h2><p>{r.address}<br/><a href={`tel:${r.phone}`}>{r.phone}</a></p><div className="attribute-list">{r.foodTypes?.map(x=><span key={x}>{x}</span>)}<span>{r.appointment?'Appointment required':'No appointment listed'}</span><span>{r.idRequired===true?'ID/documents listed':r.idRequired===false?'No ID required':'ID requirement unknown'}</span>{r.languages?.map(x=><span key={x}>{x}</span>)}<span>{r.wheelchairAccessible===true?'Accessible entrance listed':r.wheelchairAccessible===false?'Not wheelchair accessible':'Accessibility unknown'}</span></div><p><strong>Published hours:</strong> {r.schedule}</p><p>{r.attributeNote}</p><p className="verified"><strong>Last web verified:</strong> {r.checked} · Not phone confirmed</p><p><a href={r.source} target="_blank" rel="noreferrer">View source</a></p><button onClick={()=>printCard(r.id)}>Print English / Spanish card</button><section className="print-sheet"><h2>Heartfood CT / Recurso de alimentos</h2><p><strong>{r.name}</strong><br/>{r.address}<br/>{r.phone}</p><p><strong>Hours / Horario:</strong> {r.schedule}</p><p><strong>Before leaving / Antes de salir:</strong> Call to confirm hours, eligibility, documents, and food availability. / Llame para confirmar el horario, la elegibilidad, los documentos y la disponibilidad de alimentos.</p><p><strong>Verified online / Verificado en línea:</strong> {r.checked}. Not confirmed by phone / No confirmado por teléfono.</p></section></article>)}</section></main>
}
